[package]
name = "core-docs"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { workspace = true, features = ["default"] }
tracing = { workspace = true }
tower-http = { workspace = true, features = ["fs"] }
